name: C++ CI
on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Linux build tools
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            g++ \
            make \
            cmake

      - name: Setup MSVC
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install CMake (Windows)
        if: runner.os == 'Windows'
        uses: lukka/get-cmake@latest

      - name: Configure Project
        run: cmake -S . -B build

      - name: Build Project
        run: cmake --build build --config Release

      - name: Run Executable (Linux)
        if: runner.os == 'Linux'
        run: ./build/main

      - name: Run Executable (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: .\build\Release\main.exe
